add more terminal tools

diff --git a/ostreefy b/ostreefy
--- a/ostreefy
+++ b/ostreefy
@@ -23,77 +23,77 @@ export OSTREE_DEV_ROOT="${OSTREE_DEV_ROOT:-/dev/disk/by-label/${OSTREE_SYS_ROOT_
 export OSTREE_DEV_VAR="${OSTREE_DEV_VAR:-/dev/disk/by-label/${OSTREE_SYS_VAR_LABEL}}"
 
 is_local() {
-    [ -d "/ostree" ]
+	[ -d "/ostree" ]
 }
 
 env_verify_local() {
-    if ! is_local; then
-        echo "$ERROR_MSG_NON_OSTREE_ENV"
-        exit 1
-    fi
+	if ! is_local; then
+		echo "$ERROR_MSG_NON_OSTREE_ENV"
+		exit 1
+	fi
 }
 
 create_rootfs_from_container_image() {
-    if [ -z "${OSTREE_SYS_TREE}" ] || [ "${OSTREE_SYS_TREE}" = "/" ]; then
-        echo "$ERROR_MSG_OSTREE_SYS_TREE"
-        exit 1
-    fi
+	if [ -z "${OSTREE_SYS_TREE}" ] || [ "${OSTREE_SYS_TREE}" = "/" ]; then
+		echo "$ERROR_MSG_OSTREE_SYS_TREE"
+		exit 1
+	fi
 
-    rm -rf "${OSTREE_SYS_TREE}"
-    mkdir -p "${OSTREE_SYS_TREE}"
-    ${CONTAINER_RUNTIME} ${CONTAINER_RUNTIME_OPTS} export $(${CONTAINER_RUNTIME} ${CONTAINER_RUNTIME_OPTS} create "${CONTAINER_IMAGE}" sh) | tar -xC "${OSTREE_SYS_TREE}"
+	rm -rf "${OSTREE_SYS_TREE}"
+	mkdir -p "${OSTREE_SYS_TREE}"
+	${CONTAINER_RUNTIME} ${CONTAINER_RUNTIME_OPTS} export $(${CONTAINER_RUNTIME} ${CONTAINER_RUNTIME_OPTS} create "${CONTAINER_IMAGE}" sh) | tar -xC "${OSTREE_SYS_TREE}"
 
-    for script in $(find "${OSTREE_SYS_TREE}/usr/share/ostreefy/post.d" -type f | sort -t- -k1,1n); do
-        echo "Running ${script}"
-        . "${script}"
-    done
+	for script in $(find "${OSTREE_SYS_TREE}/usr/share/ostreefy/post.d" -type f | sort -t- -k1,1n); do
+		echo "Running ${script}"
+		. "${script}"
+	done
 }
 
 deploy_ostree_image() {
-    ostree commit --repo="${OSTREE_SYS_ROOT}/ostree/repo" --branch="${OSTREE_BRANCH}" --tree=dir="${OSTREE_SYS_TREE}"
-    ostree admin deploy --sysroot="${OSTREE_SYS_ROOT}" --karg="root=LABEL=SYS_ROOT" \
-        --karg="rw nvidia_drm.modeset=1 module_blacklist=nouveau" \
-        ${OSTREE_OPTS} "${OSTREE_BRANCH}"
+	ostree commit --repo="${OSTREE_SYS_ROOT}/ostree/repo" --branch="${OSTREE_BRANCH}" --tree=dir="${OSTREE_SYS_TREE}"
+	ostree admin deploy --sysroot="${OSTREE_SYS_ROOT}" --karg="root=LABEL=SYS_ROOT" \
+		--karg="rw nvidia_drm.modeset=1 module_blacklist=nouveau" --os=${OSTREE_OS} \
+		${OSTREE_OPTS} "${OSTREE_BRANCH}"
 }
 
 revert_ostree_image() {
-    ostree admin undeploy --sysroot="${OSTREE_SYS_ROOT}" 0
+	ostree admin undeploy --sysroot="${OSTREE_SYS_ROOT}" 0
 }
 
 disk_create_mounts() {
-    mount --mkdir "${OSTREE_DEV_ROOT}" "${OSTREE_SYS_ROOT}"
-    mount --mkdir "${OSTREE_DEV_BOOT}" "${OSTREE_SYS_ROOT}/boot/efi"
+	mount --mkdir "${OSTREE_DEV_ROOT}" "${OSTREE_SYS_ROOT}"
+	mount --mkdir "${OSTREE_DEV_BOOT}" "${OSTREE_SYS_ROOT}/boot/efi"
 }
 
 ostree_create_repo() {
-    ostree admin init-fs --sysroot="${OSTREE_SYS_ROOT}" --modern "${OSTREE_SYS_ROOT}"
-    ostree admin stateroot-init --sysroot="${OSTREE_SYS_ROOT}" "${OSTREE_OS}"
-    ostree init --repo="${OSTREE_SYS_ROOT}/ostree/repo" --mode=bare
-    ostree config --repo="${OSTREE_SYS_ROOT}/ostree/repo" set sysroot.bootprefix "true"
+	ostree admin init-fs --sysroot="${OSTREE_SYS_ROOT}" --modern "${OSTREE_SYS_ROOT}"
+	ostree admin stateroot-init --sysroot="${OSTREE_SYS_ROOT}" "${OSTREE_OS}"
+	ostree init --repo="${OSTREE_SYS_ROOT}/ostree/repo" --mode=bare
+	ostree config --repo="${OSTREE_SYS_ROOT}/ostree/repo" set sysroot.bootprefix "true"
 }
 
 bootloader_create() {
-    grub-install --target=x86_64-efi --efi-directory="${OSTREE_SYS_ROOT}/boot/efi" --removable --boot-directory="${OSTREE_SYS_ROOT}/boot/efi/EFI" --bootloader-id="${OSTREE_OS}" "${OSTREE_DEV_BOOT}"
+	grub-install --target=x86_64-efi --efi-directory="${OSTREE_SYS_ROOT}/boot/efi" --removable --boot-directory="${OSTREE_SYS_ROOT}/boot/efi/EFI" --bootloader-id="${OSTREE_OS}" "${OSTREE_DEV_BOOT}"
 
-    export OSTREE_SYS_PATH=$(ls -d "${OSTREE_SYS_ROOT}/ostree/deploy/${OSTREE_OS}/deploy/"* | head -n 1)
+	export OSTREE_SYS_PATH=$(ls -d "${OSTREE_SYS_ROOT}/ostree/deploy/${OSTREE_OS}/deploy/"* | head -n 1)
 
-    rm -rfv "${OSTREE_SYS_PATH}/boot/"*
-    mount --mkdir --rbind "${OSTREE_SYS_ROOT}/boot" "${OSTREE_SYS_PATH}/boot"
-    mount --mkdir --rbind "${OSTREE_SYS_ROOT}/ostree" "${OSTREE_SYS_PATH}/sysroot/ostree"
+	rm -rfv "${OSTREE_SYS_PATH}/boot/"*
+	mount --mkdir --rbind "${OSTREE_SYS_ROOT}/boot" "${OSTREE_SYS_PATH}/boot"
+	mount --mkdir --rbind "${OSTREE_SYS_ROOT}/ostree" "${OSTREE_SYS_PATH}/sysroot/ostree"
 
-    for i in /dev /proc /sys; do mount -o bind "$i" "${OSTREE_SYS_PATH}${i}"; done
-    chroot "${OSTREE_SYS_PATH}" /bin/bash -c "grub-mkconfig -o /boot/efi/EFI/grub/grub.cfg"
+	for i in /dev /proc /sys; do mount -o bind "$i" "${OSTREE_SYS_PATH}${i}"; done
+	chroot "${OSTREE_SYS_PATH}" /bin/bash -c "grub-mkconfig -o /boot/efi/EFI/grub/grub.cfg"
 
-    umount -R "${OSTREE_SYS_ROOT}"
+	umount -R "${OSTREE_SYS_ROOT}"
 }
 
 check_programs() {
-    for P in "$@"; do
-        if ! command -v "${P}" > /dev/null 2>&1; then
-            echo "ERROR: Required program '${P}' is not installed."
-            exit 1
-        fi
-    done
+	for P in "$@"; do
+		if ! command -v "${P}" >/dev/null 2>&1; then
+			echo "ERROR: Required program '${P}' is not installed."
+			exit 1
+		fi
+	done
 }
 
 check_programs ostree ${CONTAINER_RUNTIME} wget which grub-install
@@ -102,35 +102,35 @@ OPERATION=${1:-}
 CONTAINER_IMAGE=${2:-}
 
 if [ -z "$CONTAINER_IMAGE" ] && [ "$OPERATION" != "revert" ]; then
-    echo "ERROR: Container Image not provided."
-    exit 1
+	echo "ERROR: Container Image not provided."
+	exit 1
 fi
 
 case ${OPERATION} in
-    install)
-        disk_create_mounts
-        ostree_create_repo
-        create_rootfs_from_container_image
-        deploy_ostree_image
-        bootloader_create
-    ;;
-    upgrade)
-        env_verify_local
-        create_rootfs_from_container_image
-        deploy_ostree_image
-    ;;
-    revert)
-        env_verify_local
-        revert_ostree_image
-    ;;
-    *)
-        HELP="Usage:
+install)
+	disk_create_mounts
+	ostree_create_repo
+	create_rootfs_from_container_image
+	deploy_ostree_image
+	bootloader_create
+	;;
+upgrade)
+	env_verify_local
+	create_rootfs_from_container_image
+	deploy_ostree_image
+	;;
+revert)
+	env_verify_local
+	revert_ostree_image
+	;;
+*)
+	HELP="Usage:
   ostreefy [flavour] [operation]
 Operations:
   install : (Install deployment) : Install to a new disk.
   upgrade : (Update deployment) : Creates a new OSTree commit.
   revert  : (Update deployment) : Rolls back version 0."
 
-        printf '%s\n' "$HELP"
-    ;;
+	printf '%s\n' "$HELP"
+	;;
 esac
